### PR TITLE
Updating README.md

### PR DESCRIPTION
**Pull request by sushmavankayala**
Updated README.md file with the below details:

- the project type
- the questions of interest
- the goal for the project output (what are you going to produce?)
- the data sources you will use

### CODE REVIEW

**Comment by BrunoB42** [comment]
Looks mostly good! However, it might be better to use this https://transtats.bts.gov/Tables.asp?QO_VQ=EFD&QO_anzr=Nv4yv0r%FDb0-gvzr%FDcr4s14zn0pr%FDQn6n&QO_fu146_anzr=b0-gvzr as the source for the flight delay information instead of the overall BTS aviation page!

**Comment by fangyulim** [comment]
It looks great!

**Review by BrunoB42 — APPROVED** [review]
Everything looks good! New link should our sources pretty obvious to any readers!

**Review by fangyulim — APPROVED** [review]
It looks good.

**Pull request merged**
